### ISSUE TITLE
Actividad 11 - Proyecto final RA

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-11-proyecto-final-de-realidad-aumentada-promastergamer#1]

**Comment by Heidi-19** [comment]
[Actividad 11 - Proyecto Final RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-proyecto-final-de-realidad-aumentada-promastergamer/files/15370372/Actividad.11.-.Proyecto.Final.RA.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificacion 20
